import Foundation

/// Pixel-art dinosaur — an orange 8-bit T-rex traced from a 44×44 reference —
/// plus the prey it chases and the meat it eats.
///
/// Legend — dino: '.' clear   'o' orange       'O' light orange   'r' red
///                'd' dark-red outline   'y' yellow belly   'g' green patch
///                'b' blue (eye / feet)  'k' black (pupil / nostril)  'w' eye-white
///          prey: 'c' outline  'C' purple body  ('w'/'k' for its eye)
///          meat: 'm' edge     'M' meat         'B' bone
///
/// Faces RIGHT; PetView mirrors it to walk left. The walk gait cycles
/// [walkB, stand, walkC, stand] — lifting the back foot, passing, then the
/// front foot — so both feet step. `blink` shuts the eye.
enum DinoPixelArt {
    static let width = 44
    static let height = 44

    static let stand: [String] = [
        ".............................rrrr..rrrO.....",
        "...........................rroooorrroorO....",
        "..........................OrrooooooooorO....",
        ".........................OroorrrryyyoorO....",
        ".........................OrorbbrdroyyorrOO..",
        "........................OorobbbgkbooOyOrrrO.",
        ".......................OoooobbbkkbooooOyyyrO",
        ".......................ooooorbbbbooooodkoyyr",
        ".......................oooooooooooooooodkood",
        ".......................roooooOOOoooooooooood",
        ".......................rddoOOOOOrooooooooood",
        "........................ddooOOOOyrrrrrrrrrrr",
        "........................rdoooOOOOOyyyyyyyyO.",
        ".........................rddooooooooOOOOOy..",
        ".........................rddoooooOOO........",
        "...........................doooooOO.........",
        "...........................doooooOO.........",
        "...........................doooooyO.........",
        "..........................roooooOyO.........",
        ".......................rrrooooooyyO.........",
        "r...................rrrooooyooooyyO.........",
        "rOy..............rrroooooooyooooyyO.........",
        "rOy.............rroooOOoyyooooooyyo.........",
        "rOOr............rroooyyoooooooryygd.........",
        "dOOr...........rrooyyoooooorooryggd.........",
        "dooor.........rroyoooooooooroorgggddO.......",
        "dooor.........rOyorrrroooooroorgggoooO......",
        ".door........rOOoooyyyroooooroorrgddodg.....",
        ".doooo.......rOOOyyyyyyroooodooood.dodg.....",
        ".dooOyo.....roOoOOyyyyyrorrrgdoood..rdg.....",
        "..doOyyr...roOOoOOyyyyyyrdyygggdod..rO......",
        "..gdoooorrroOOOoOOOOyyyyryyygggddd..........",
        "...doooooooOOOooOOOOyyyyrgggggg.d...........",
        "...ddoooooOOOooooOOOyyyyrgggggg.............",
        "....ddoooooooddggddOOyyyrgggggr.............",
        ".....ddooodddgggggdOOyyrgggddor.............",
        "......ddOgggggggggdOyyyrdddooor.............",
        ".......ddgggggddddoOyyrOdddood..............",
        ".........dddddO..doOyrOOdoood...............",
        "...........OOO...doOOrOOdoood...............",
        ".................doOOOoooooodrr.............",
        ".................doooooobbooooobr...........",
        ".................doooooobbboooobrb..........",
        ".................dddddddbbbddddbbb..........",
    ]

    static let walkB: [String] = [
        ".............................rrrr..rrrO.....",
        "...........................rroooorrroorO....",
        "..........................OrrooooooooorO....",
        ".........................OroorrrryyyoorO....",
        ".........................OrorbbrdroyyorrOO..",
        "........................OorobbbgkbooOyOrrrO.",
        ".......................OoooobbbkkbooooOyyyrO",
        ".......................ooooorbbbbooooodkoyyr",
        ".......................oooooooooooooooodkood",
        ".......................roooooOOOoooooooooood",
        ".......................rddoOOOOOrooooooooood",
        "........................ddooOOOOyrrrrrrrrrrr",
        "........................rdoooOOOOOyyyyyyyyO.",
        ".........................rddooooooooOOOOOy..",
        ".........................rddoooooOOO........",
        "...........................doooooOO.........",
        "...........................doooooOO.........",
        "...........................doooooyO.........",
        "..........................roooooOyO.........",
        ".......................rrrooooooyyO.........",
        "r...................rrrooooyooooyyO.........",
        "rOy..............rrroooooooyooooyyO.........",
        "rOy.............rroooOOoyyooooooyyo.........",
        "rOOr............rroooyyoooooooryygd.........",
        "dOOr...........rrooyyoooooorooryggd.........",
        "dooor.........rroyoooooooooroorgggddO.......",
        "dooor.........rOyorrrroooooroorgggoooO......",
        ".door........rOOoooyyyroooooroorrgddodg.....",
        ".doooo.......rOOOyyyyyyroooodooood.dodg.....",
        ".dooOyo.....roOoOOyyyyyrorrrgdoood..rdg.....",
        "..doOyyr...roOOoOOyyyyyyrdyygggdod..rO......",
        "..gdoooorrroOOOoOOOOyyyyryyygggddd..........",
        "...doooooooOOOooOOOOyyyyrgggggg.d...........",
        "...ddoooooOOOooooOOOyyyyrgggggg.............",
        "....ddoooooooddggddOOyyyrgggggr.............",
        ".....ddooodddgggggdOOyyrgggddor.............",
        "......ddOgggggggggdOyyyrdddooor.............",
        ".......ddgggggddddoOyyrOdddood..............",
        ".........dddddO..doOyrOoooooo...............",
        "...........OOO...doOOrOoobboo...............",
        ".................doOOO.oobbborr.............",
        ".................doooo.ddbbbdoobr...........",
        ".................doooo......ooobrb..........",
        ".................ddddd......dddbbb..........",
    ]

    static let walkC: [String] = [
        ".............................rrrr..rrrO.....",
        "...........................rroooorrroorO....",
        "..........................OrrooooooooorO....",
        ".........................OroorrrryyyoorO....",
        ".........................OrorbbrdroyyorrOO..",
        "........................OorobbbgkbooOyOrrrO.",
        ".......................OoooobbbkkbooooOyyyrO",
        ".......................ooooorbbbbooooodkoyyr",
        ".......................oooooooooooooooodkood",
        ".......................roooooOOOoooooooooood",
        ".......................rddoOOOOOrooooooooood",
        "........................ddooOOOOyrrrrrrrrrrr",
        "........................rdoooOOOOOyyyyyyyyO.",
        ".........................rddooooooooOOOOOy..",
        ".........................rddoooooOOO........",
        "...........................doooooOO.........",
        "...........................doooooOO.........",
        "...........................doooooyO.........",
        "..........................roooooOyO.........",
        ".......................rrrooooooyyO.........",
        "r...................rrrooooyooooyyO.........",
        "rOy..............rrroooooooyooooyyO.........",
        "rOy.............rroooOOoyyooooooyyo.........",
        "rOOr............rroooyyoooooooryygd.........",
        "dOOr...........rrooyyoooooorooryggd.........",
        "dooor.........rroyoooooooooroorgggddO.......",
        "dooor.........rOyorrrroooooroorgggoooO......",
        ".door........rOOoooyyyroooooroorrgddodg.....",
        ".doooo.......rOOOyyyyyyroooodooood.dodg.....",
        ".dooOyo.....roOoOOyyyyyrorrrgdoood..rdg.....",
        "..doOyyr...roOOoOOyyyyyyrdyygggdod..rO......",
        "..gdoooorrroOOOoOOOOyyyyryyygggddd..........",
        "...doooooooOOOooOOOOyyyyrgggggg.d...........",
        "...ddoooooOOOooooOOOyyyyrgggggg.............",
        "....ddoooooooddggddOOyyyrgggggr.............",
        ".....ddooodddgggggdOOyyrgggddor.............",
        "......ddOgggggggggdOyyyrdddooor.............",
        ".......ddgggggddddoOyyrOdddood..............",
        ".........dddddO..doOyrOOdoood.rr............",
        "...........OOO...doOOrOOdoood.oobr..........",
        ".................doOOOooooood.oobrb.........",
        ".................doooooobbooo.ddbbb.........",
        ".................doooooobbboo...............",
        ".................dddddddbbbdd...............",
    ]

    static let blink: [String] = [
        ".............................rrrr..rrrO.....",
        "...........................rroooorrroorO....",
        "..........................OrrooooooooorO....",
        ".........................OroorrrryyyoorO....",
        ".........................OroroordroyyorrOO..",
        "........................OorddddddddoOyOrrrO.",
        ".......................OooooooooooooooOyyyrO",
        ".......................ooooorooooooooodkoyyr",
        ".......................oooooooooooooooodkood",
        ".......................roooooOOOoooooooooood",
        ".......................rddoOOOOOrooooooooood",
        "........................ddooOOOOyrrrrrrrrrrr",
        "........................rdoooOOOOOyyyyyyyyO.",
        ".........................rddooooooooOOOOOy..",
        ".........................rddoooooOOO........",
        "...........................doooooOO.........",
        "...........................doooooOO.........",
        "...........................doooooyO.........",
        "..........................roooooOyO.........",
        ".......................rrrooooooyyO.........",
        "r...................rrrooooyooooyyO.........",
        "rOy..............rrroooooooyooooyyO.........",
        "rOy.............rroooOOoyyooooooyyo.........",
        "rOOr............rroooyyoooooooryygd.........",
        "dOOr...........rrooyyoooooorooryggd.........",
        "dooor.........rroyoooooooooroorgggddO.......",
        "dooor.........rOyorrrroooooroorgggoooO......",
        ".door........rOOoooyyyroooooroorrgddodg.....",
        ".doooo.......rOOOyyyyyyroooodooood.dodg.....",
        ".dooOyo.....roOoOOyyyyyrorrrgdoood..rdg.....",
        "..doOyyr...roOOoOOyyyyyyrdyygggdod..rO......",
        "..gdoooorrroOOOoOOOOyyyyryyygggddd..........",
        "...doooooooOOOooOOOOyyyyrgggggg.d...........",
        "...ddoooooOOOooooOOOyyyyrgggggg.............",
        "....ddoooooooddggddOOyyyrgggggr.............",
        ".....ddooodddgggggdOOyyrgggddor.............",
        "......ddOgggggggggdOyyyrdddooor.............",
        ".......ddgggggddddoOyyrOdddood..............",
        ".........dddddO..doOyrOOdoood...............",
        "...........OOO...doOOrOOdoood...............",
        ".................doOOOoooooodrr.............",
        ".................doooooobbooooobr...........",
        ".................doooooobbboooobrb..........",
        ".................dddddddbbbddddbbb..........",
    ]

    // MARK: - Props

    static let prey: [String] = [
        "...........",
        "......ccc..",
        "....ccCCCc.",
        "...cCCCCwkc",
        "...cCCCCCCc",
        "...cCCCCCc.",
        "....c.cc.c.",
        "...........",
    ]

    static let meat: [String] = [
        "..mmmm..",
        ".mMMMMm.",
        ".mMMMMm.",
        ".mMMMMm.",
        "..mmm...",
        "...BB...",
        "....BB..",
    ]
}
